device: 'cuda:0'
optim: 'adamw'
momentum: 0.9
eps: 1e-8
lr: 1e-4
minlr: 1e-6
beta1: 0.9
beta2: 0.999
weight_decay: 5e-2
epoch: 60
accumulation_steps: 1
warm_epoch: 0
warm_lr: 1e-3
save_model_fre: 20
batch_size: 8

emd_dim: 768
drop_out: 0.1
backbone_net: 'mvit_s_two'
fused_posi: 1

shape: [224, 224]
output_root: 

file_train: 
file_val: 
file_test: 
input: 
keypoints_body_path: 
dataset: "wlasl100"
datadir: 
num_frames: 16
frames_per_group: 1
num_clips: 1
num_class: 100
modality: 'rgb'
dense_sampling: False
resume: False
resume_path: 


